[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzepelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
 sepolia = "${SEPOLIA_RPC_URL}"
 mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
